checks:
    php: true
    javascript: true
filter:
    excluded_paths:
        - '*.min.js'
coding_style:
    php:
        spaces:
            around_operators:
                additive: false
            before_keywords:
                else: false
build: true
