---
Name: seotoolboxroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'seotest'                 : 'SEOTestSiteTreeController'
    'AutomatedLinkReportTask' : 'AutomatedLinkReportTask'
